[package]
name = "spdx-blaster"
version = "0.1.1"
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.33.1"
log = "0.4.8"
env_logger = "0.7.1"
memmap = "0.7.0"
